sudo: false
language: node_js
os:
  - linux
  - osx
node_js:
  - 6
  - 7
  - 8

cache:
  bundle: true
  directories:
    - node_modules

install:
  - npm install

before_script: npm install codecov
script: npm test -- --coverage
after_script: codecov --token=$CODECOV_TOKEN
